name: Latest blog & stackoverflow posts
on: 
    schedule:
        - cron: '0 1 * * *'
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write # To write the generated contents to the readme
  
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with the latest blog & stackoverflow posts
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4
            - name: Pull from Medium Blog
              uses: gautamkrishnar/blog-post-workflow@v1
              with: 
                max_post_count: "10"
                feed_names: "Medium,Stackoverflow"
                feed_list: "https://medium.com/feed/@gchandra,https://stackoverflow.com/feeds/user/11086515"
